masterpi/app/users/views.py
import requests, json
import os
import pickle
import json
import numpy as np
import qrcode

from json import JSONEncoder
from multiprocessing import Process
from flask import Blueprint, request, render_template, flash, g, session, redirect, url_for, current_app
from werkzeug.security import check_password_hash, generate_password_hash
from sqlalchemy import or_
from werkzeug.utils import secure_filename
from flask_login import (
    current_user,
    login_required,
    login_user,
    logout_user,
)

from ..facial_recognition.encode_faces import encode
from app import db, login_manager, client
from app.users.forms import RegisterForm, LoginForm, UserForm, UserEditForm, PhotosForm
from app.users.models import User
from app.cars.models import Car, CarReport
from app.cars.forms import CarForm
from app.bookings.models import Booking
# from app.users.decorators import login_required

mod = Blueprint('users', __name__, url_prefix='/')
api_mod = Blueprint('users_api', __name__, url_prefix='/api')
UPLOAD_FOLDER_URL = 'app/facial_recognition/dataset'
QR_UPLOAD_FOLDER_URL = 'app/qr_code'

class NumpyArrayEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, np.integer):
            return int(obj)
        elif isinstance(obj, np.floating):
            return float(obj)
        elif isinstance(obj, np.ndarray):
            return obj.tolist()
        else:
            return super(NumpyArrayEncoder, self).default(obj)

def generate_qr_code(old_engineer_name, new_engineer_name):
    print(old_engineer_name)
    if old_engineer_name != '':
        oldfilename = old_engineer_name + '.png'
        dir = os.path.join(QR_UPLOAD_FOLDER_URL, oldfilename)
        if os.path.exists(dir):
            os.remove(dir)
    
    newfilename = new_engineer_name + '.png'
    directory = os.path.join(QR_UPLOAD_FOLDER_URL, newfilename)
    img = qrcode.make(new_engineer_name)
    img.save(directory)
    
@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

@login_manager.unauthorized_handler
def unauthorized():
    return redirect(url_for('users.login'))

@mod.route('/')
@login_required
def home():
    bookings = Booking.query.filter_by(user_id=current_user.id) \
                            .order_by(Booking.id.desc()).all()
    return render_template("users/home.html", user=current_user, bookings=bookings)

@mod.route('/login/', methods=['GET', 'POST'])
def login():
    """
    Login form
    """
    if current_user.is_authenticated:
        return redirect(url_for('users.login_redirect'))
    form = LoginForm(request.form)
    # make sure data are valid, but doesn't validate password is right
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        # we use werzeug to validate user's password
        if user and check_password_hash(user.password, form.password.data):
            # the session can't be modified as it's signed, 
            # it's a safe place to store the user id
            login_user(user)
            flash('Welcome %s' % user.username)
            return redirect(url_for('users.home'))
        flash('Wrong username or password', 'error-message')
    return render_template("users/login.html", form=form)

@mod.route('/google-login/', methods=['GET'])
def google_login():
    if current_user.is_authenticated:
        return redirect(url_for('users.login_redirect'))    
    #ref: https://realpython.com/flask-google-login/
    #TODO: check if user's is logged in
    google_provider_cfg = requests.get(current_app.config['GOOGLE_DISCOVERY_URL']).json()
    authorization_endpoint = google_provider_cfg["authorization_endpoint"]
    request_uri = client.prepare_request_uri(
        authorization_endpoint,
        redirect_uri=url_for('users.google_callback', _external=True),
        scope=["openid", "email", "profile"],
    )
    return redirect(request_uri)

@mod.route('/google-login/callback', methods=['GET'])
def google_callback():
    #ref: https://realpython.com/flask-google-login/
    code = request.args.get("code")
    google_provider_cfg = requests.get(current_app.config['GOOGLE_DISCOVERY_URL']).json()
    token_endpoint = google_provider_cfg["token_endpoint"]
    token_url, headers, body = client.prepare_token_request(
        token_endpoint,
        authorization_response=request.url,
        redirect_url=request.base_url,
        code=code
    )
    token_response = requests.post(
        token_url,
        headers=headers,
        data=body,
        auth=(current_app.config['GOOGLE_CLIENT_ID'], 
              current_app.config['GOOGLE_CLIENT_SECRET']),
    )

    # Parse the tokens!
    client.parse_request_body_response(json.dumps(token_response.json()))

    userinfo_endpoint = google_provider_cfg["userinfo_endpoint"]
    uri, headers, body = client.add_token(userinfo_endpoint)
    userinfo_response = requests.get(uri, headers=headers, data=body).json()
    user = User.query.filter_by(email=userinfo_response['email']).first()
    if not user:
        user = User(userinfo_response['email'],
                    username=userinfo_response['sub'], 
                    first_name=userinfo_response['given_name'],
                    last_name=userinfo_response['family_name'])
        db.session.add(user)
        db.session.commit()
    login_user(user)
    return redirect(url_for('users.home'))

@mod.route('/login/redirect')
@login_required
def login_redirect():
    if current_user.isEngineer():
        return redirect(url_for('users.engineer'))
    if current_user.isManager() or current_user.isAdmin():
        return redirect(url_for('users.dashboard'))
    return redirect(url_for('users.home'))
 
@mod.route('/logout/')
@login_required
def logout():
    logout_user()
    return redirect(url_for('users.login'))
  
@mod.route('/register/', methods=['GET', 'POST'])
def register():
    """
    Registration Form
    """
    if current_user.is_authenticated:
        return redirect(url_for('users.login_redirect'))    
    form = RegisterForm(request.form)
    if form.validate_on_submit():
        # check whether if there is user with the same username/email
        user = User.query.filter(or_(User.username == form.username.data, 
                                     User.email == form.email.data)).first()
        if not user:
            # create an user instance not yet stored in the database
            user = User(form.email.data, 
                        username=form.username.data, 
                        first_name=form.first_name.data, 
                        last_name=form.last_name.data, 
                        password=generate_password_hash(form.password.data))
            # Insert the record in our database and commit it
            db.session.add(user)
            db.session.commit()

            # Log the user in, as he now has an id
            login_user(user)

            # flash will display a message to the user
            flash('Thanks for registering')
            # redirect user to the 'home' method of the user module.
            return redirect(url_for('users.login_redirect'))
        flash('Username or email is taken.')
    return render_template("users/register.html", form=form)

@mod.route('/dashboard/')
@login_required
def dashboard():
    return render_template("users/dashboard.html")
    
@mod.route('/engineer/')
@login_required
def engineer():
    return render_template("users/engineer.html")
  
@mod.route('/admin/bookings', methods=['GET'])
@login_required
def admin_bookings():
    if not current_user.isAdmin():
        return "503 Not sufficent permission"
    bookings = Booking.query.all()
    return render_template("users/admin/bookings.html", bookings=bookings)

@mod.route('/admin/cars', methods=['GET'])
@login_required
def admin_cars():
    if not current_user.isAdmin():
        return "503 Not sufficent permission"
    cars = Car.query.all()
    return render_template("users/admin/cars.html", cars=cars)

@mod.route('/admin/cars/create', methods=['GET', 'POST'])
@login_required
def admin_cars_create():
    if not current_user.isAdmin():
        return "503 Not sufficent permission"
    form = CarForm(request.form)
    if form.validate_on_submit():
        car = Car(make=form.make.data, 
                  color=form.color.data,
                  body_type=form.body_type.data,
                  seats=form.seats.data,
                  cost_per_hour=form.cost_per_hour.data)
        # Insert the record in our database and commit it
        db.session.add(car)
        db.session.commit()
        flash('Car added.')
        return redirect(url_for('users.admin_cars_create'))
        # redirect user to the 'home' method of the user module.    
    return render_template("users/admin/cars-create.html", form=form)    

@mod.route('/admin/cars/edit/<car_id>', methods=['GET', 'POST'])
@login_required
def admin_cars_edit(car_id):
    if not current_user.isAdmin():
        return "503 Not sufficent permission"
    car = Car.query.filter_by(id=car_id).first()
    if not car: 
        return "400 car not exists"
    form = CarForm(obj=car)
    if form.validate_on_submit():
        form.populate_obj(car)
        db.session.commit()
        flash('Car information updated.')
    return render_template("users/admin/cars-edit.html", form=form)

@mod.route('/admin/cars/delete', methods=['POST'])
@login_required
def admin_cars_delete():
    if not current_user.isAdmin():
        return "503 Not sufficent permission", 503
    car = Car.query.filter_by(id=request.form['car_id']).first()
    if car:
        db.session.delete(car)
        db.session.commit()
        return '', 200
    return 'car not exist.', 404

@mod.route('/admin/cars/report', methods=['POST'])
@login_required
def admin_cars_report():
    if not current_user.isAdmin():
        return "503 Not sufficent permission", 503
    car = Car.query.filter_by(id=request.form['car_id']).first()
    if car:

masterpi/app/templates/base.html
<!-- HEADER -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">    
    <title>{% block title %}Car Share IOT{% endblock %}</title>
    {% block css %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}" media="screen">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" media="screen">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/custom.css') }}" media="screen">
    {% endblock %}
</head>
<body>
<!-- END_HEADER -->

{% if current_user.is_authenticated %}
<!-- NAVBAR -->
<div class="navbar navbar-expand-lg navbar-dark bg-primary">
	<div class="container"> <b class="navbar-brand">Car Share IOT</b>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"> <span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarResponsive">
			<ul class="navbar-nav mr-auto">
				<li class="nav-item"><a class="nav-link" href="{{ url_for('users.home') }}">Home</a></li>
				{% if current_user.isAdmin() or current_user.isManager() %}
					<li class="nav-item"><a class="nav-link" href="{{ url_for('users.dashboard') }}">Dashboard</a></li>
				{% endif %}
				{% if current_user.isAdmin() %}
					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Admin pages</a>
						<div class="dropdown-menu">
						<a class="dropdown-item" href="{{ url_for('users.admin_cars') }}">Cars</a>
						<a class="dropdown-item" href="{{ url_for('users.admin_users') }}">Users</a>
						<a class="dropdown-item" href="{{ url_for('users.admin_bookings') }}">Bookings</a>
						</div>
					</li>
				{% endif %}
				{% if current_user.isEngineer() %}
					<li class="nav-item"><a class="nav-link" href="{{ url_for('users.engineer') }}">Engineer page</a></li>
				{% endif %}
				<li class="nav-item"><a class="nav-link" href="{{ url_for('users.logout') }}">Logout</a></li>
			</ul>
			<div class="form-inline my-2 my-lg-0">
				<a href="{{ url_for('cars.index') }}" class="btn btn-secondary my-2 my-sm-0" type="submit">
					<i class="fa fa-car" aria-hidden="true"></i> Book a car
				</a>
			</div>
		</div>
	</div>
</div>
<!-- END_NAVBAR -->
{% endif %}

<div class="container main">
{% block content %}{% endblock %}

<footer id="footer">
    <div class="row">
      <div class="col-lg-12">
        <ul class="list-unstyled">
          <li class="float-lg-right"><a href="#top">Scroll to top <i class="fa fa-arrow-up" aria-hidden="true"></i></a></li>
          <li>Made with <i style="color:red" class="fa fa-heart"></i> by RMIT students.</li>
        </ul>
      </div>
    </div>
  </footer>
</div>

<!-- FOOTER -->
{% block script %}
<script src="{{ url_for('static', filename='js/jquery.min.js') }}" type="text/javascript"></script>
<script src="{{ url_for('static', filename='js/bootstrap.min.js') }}" type="text/javascript"></script>
<script src="{{ url_for('static', filename='js/custom.js') }}" type="text/javascript"></script>
{% endblock %}
</body>
</html>
<!-- END_FOOTer -->

masterpi/app/templates/home.html
{% include "layouts/header.html" %}

    <div class="container">
        <div class="bs-docs-section">
            <div class="row">
            <div class="col-lg-6 d-none d-lg-block">
                <div class="page-header">
                <h1 id="forms">Car Share IOT</h1>
                <img src="{{ url_for('static', filename='img/hero.svg') }}" class="img-fluid hero-img" alt="hero">
                </div>
            </div>
            <div class="col-lg-4 offset-lg-1 mx-auto" style="max-width: 400px;">
                <div class="bs-component">
                <form>
                    <fieldset>
                    <legend><b>Login</b> / <a href="{{ url_for("users.register") }}">Register</a></legend>
                    <hr class="my-4">
                    <button style="background-color:#1a73e8" type="button" class="btn btn-info btn-block">
                        <i class="fa fa-google" aria-hidden="true"></i> Sign in with Google
                    </button>
                    <hr class="my-4">
                    <div class="form-group">
                        <label for="username">Username</label>
                        <input class="form-control" id="username" placeholder="Enter username">
                    </div>
                    <div class="form-group">
                        <label for="password">Password</label>
                        <input type="password" class="form-control" id="password" placeholder="Password">
                    </div>
                    <div class="form-group">
                        <div class="custom-control custom-checkbox">
                        <input type="checkbox" class="custom-control-input" id="customCheck1" checked="">
                        <label class="custom-control-label" for="customCheck1">Remember my account</label>
                        </div>
                    </div>
                    <button type="button" class="btn btn-primary btn-block">Login</button>
                    </fieldset>
                </form>
            </div>
            </div>
        </div>
    </div>


{% include "layouts/footer.html" %}