masterpi/app/users/models.py
from app import db
from sqlalchemy.inspection import inspect
from app.users import constants as USER
from flask_login import UserMixin

class User(UserMixin, db.Model):
    __tablename__ = 'User'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(120), unique=True)
    password = db.Column(db.String(120))
    email = db.Column(db.String(100), unique=True, nullable=False)
    role = db.Column(db.SmallInteger, default=USER.CUSTOMER)
    first_name = db.Column(db.String(100))
    last_name = db.Column(db.String(100))
    bluetooth_MAC = db.Column(db.String(100), unique=True, nullable=True)
    facial_recognition = db.Column(db.Boolean, default=False)
    google_login = db.Column(db.Boolean, default=False)

    def __init__(self, email, username=None, password=None,
                       role=None, first_name=None, last_name=None, bluetooth_MAC=None):
        self.email = email
        self.username = username
        self.password = password
        self.role = role
        self.first_name = first_name
        self.last_name = last_name
        self.bluetooth_MAC = bluetooth_MAC

    def isAdmin(self):
        return self.role == 0

    def isManager(self):
        return self.role == 1

    def isEngineer(self):
        return self.role == 2

    def isCustomer(self):
        return self.role == 3

    def getRole(self):
        return USER.ROLE[self.role]

    def serialize(self):
        data = {c: getattr(self, c) for c in inspect(self).attrs.keys()}
        del data['password']
        return data

    def __repr__(self):
        return '<User %r>' % (self.email)

masterpi/app/users/forms.py
from flask_wtf import Form, RecaptchaField, FlaskForm
from wtforms import TextField, PasswordField, BooleanField, SelectField, MultipleFileField, SubmitField, FileField
from wtforms.validators import Required, EqualTo, Email
from app.users import constants as USER
from flask_wtf.file import FileAllowed, FileRequired

class LoginForm(Form):
    username = TextField('Username', [Required()])
    password = PasswordField('Password', [Required()])
    remember_me = BooleanField('Remember me')

class RegisterForm(Form):
    username = TextField('Username', [Required()])
    email = TextField('Email address', [Required(), Email()])
    password = PasswordField('Password', [Required()])
    first_name = TextField('First Name', [Required()])
    last_name = TextField('Last Name', [Required()])
    accept_tos = BooleanField('I accept the TOS', [Required()])

class UserForm(Form):
    username = TextField('Username', [Required()])
    email = TextField('Email address', [Required(), Email()])
    password = PasswordField('Password', [Required()])
    role = SelectField('Role', choices=[(0, USER.ROLE[0]), 
                                       (1, USER.ROLE[1]), 
                                       (2, USER.ROLE[2]),
                                       (3, USER.ROLE[3])])
    first_name = TextField('First Name')
    last_name = TextField('Last Name')
    bluetooth_MAC = TextField('Bluetooth MAC')

class UserEditForm(Form):
    username = TextField('Username', [Required()])
    email = TextField('Email address', [Required(), Email()])
    role = SelectField('Role', choices=[(0, USER.ROLE[0]), 
                                       (1, USER.ROLE[1]), 
                                       (2, USER.ROLE[2]),
                                       (3, USER.ROLE[3])])
    first_name = TextField('First Name')
    last_name = TextField('Last Name')
    bluetooth_MAC = TextField('bluetooth MAC')

class PhotosForm(FlaskForm):
    images = FileField('Images', render_kw={'multiple':True},
    validators=[
        FileRequired(),
        FileAllowed(['jpg', 'png'], 'jpg, png files only!')
    ])

masterpi/app/cars/views.py
from flask import Blueprint, request, render_template, flash, g, session, redirect, url_for

from app import db
from app.cars.models import Car, CarReport
from app.cars.forms import searchForm


mod = Blueprint('cars', __name__, url_prefix='/cars')


@mod.route('/details/<id>', methods=['GET'])
def details(id):
    car = Car.query.filter_by(id=id).first()
    if car:
        return render_template("cars/details.html", car=car)
    return render_template("404.html")


@mod.route('/show-cars', methods=['GET'])
def show_all_cars(): 
    cars = Car.query.all()
    if cars:
        return render_template("cars/cars.html", cars=cars)
    return "There is no available car at the moment"


@mod.route('/search-cars', methods=['GET', 'POST'])
#TODO: implement https://sqlalchemy-searchable.readthedocs.io/en/latest/integrations.html or https://pythonhosted.org/Flask-WhooshAlchemy/
def search_cars():
    form = searchForm(request.form)
    car = Car.query.search(form.keyWord).all()
    if car:
        return render_template("cars/details.html", car=car)
    return render_template("404.html")

masterpi/app/users/views.py
import requests, json
import os
import pickle
import json
import numpy as np
import qrcode

from json import JSONEncoder
from multiprocessing import Process
from flask import Blueprint, request, render_template, flash, g, session, redirect, url_for, current_app
from werkzeug.security import check_password_hash, generate_password_hash
from sqlalchemy import or_
from werkzeug.utils import secure_filename
from flask_login import (
    current_user,
    login_required,
    login_user,
    logout_user,
)

from ..facial_recognition.encode_faces import encode
from app import db, login_manager, client
from app.users.forms import RegisterForm, LoginForm, UserForm, UserEditForm, PhotosForm
from app.users.models import User
from app.cars.models import Car, CarReport
from app.cars.forms import CarForm
from app.bookings.models import Booking
# from app.users.decorators import login_required

mod = Blueprint('users', __name__, url_prefix='/')
api_mod = Blueprint('users_api', __name__, url_prefix='/api')
UPLOAD_FOLDER_URL = 'app/facial_recognition/dataset'
QR_UPLOAD_FOLDER_URL = 'app/qr_code'

class NumpyArrayEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, np.integer):
            return int(obj)
        elif isinstance(obj, np.floating):
            return float(obj)
        elif isinstance(obj, np.ndarray):
            return obj.tolist()
        else:
            return super(NumpyArrayEncoder, self).default(obj)

def generate_qr_code(old_engineer_name, new_engineer_name):
    print(old_engineer_name)
    if old_engineer_name != '':
        oldfilename = old_engineer_name + '.png'
        dir = os.path.join(QR_UPLOAD_FOLDER_URL, oldfilename)
        if os.path.exists(dir):
            os.remove(dir)
    
    newfilename = new_engineer_name + '.png'
    directory = os.path.join(QR_UPLOAD_FOLDER_URL, newfilename)
    img = qrcode.make(new_engineer_name)
    img.save(directory)
    
@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

@login_manager.unauthorized_handler
def unauthorized():
    return redirect(url_for('users.login'))

@mod.route('/')
@login_required
def home():
    bookings = Booking.query.filter_by(user_id=current_user.id) \
                            .order_by(Booking.id.desc()).all()
    return render_template("users/home.html", user=current_user, bookings=bookings)

@mod.route('/login/', methods=['GET', 'POST'])
def login():
    """
    Login form
    """
    if current_user.is_authenticated:
        return redirect(url_for('users.login_redirect'))
    form = LoginForm(request.form)
    # make sure data are valid, but doesn't validate password is right
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        # we use werzeug to validate user's password
        if user and check_password_hash(user.password, form.password.data):
            # the session can't be modified as it's signed, 
            # it's a safe place to store the user id
            login_user(user)
            flash('Welcome %s' % user.username)
            return redirect(url_for('users.home'))
        flash('Wrong username or password', 'error-message')
    return render_template("users/login.html", form=form)

@mod.route('/google-login/', methods=['GET'])
def google_login():
    if current_user.is_authenticated:
        return redirect(url_for('users.login_redirect'))    
    #ref: https://realpython.com/flask-google-login/
    #TODO: check if user's is logged in
    google_provider_cfg = requests.get(current_app.config['GOOGLE_DISCOVERY_URL']).json()
    authorization_endpoint = google_provider_cfg["authorization_endpoint"]
    request_uri = client.prepare_request_uri(
        authorization_endpoint,
        redirect_uri=url_for('users.google_callback', _external=True),
        scope=["openid", "email", "profile"],
    )
    return redirect(request_uri)

@mod.route('/google-login/callback', methods=['GET'])
def google_callback():
    #ref: https://realpython.com/flask-google-login/
    code = request.args.get("code")
    google_provider_cfg = requests.get(current_app.config['GOOGLE_DISCOVERY_URL']).json()
    token_endpoint = google_provider_cfg["token_endpoint"]
    token_url, headers, body = client.prepare_token_request(
        token_endpoint,
        authorization_response=request.url,
        redirect_url=request.base_url,
        code=code
    )
    token_response = requests.post(
        token_url,
        headers=headers,
        data=body,
        auth=(current_app.config['GOOGLE_CLIENT_ID'], 
              current_app.config['GOOGLE_CLIENT_SECRET']),
    )

    # Parse the tokens!
    client.parse_request_body_response(json.dumps(token_response.json()))

    userinfo_endpoint = google_provider_cfg["userinfo_endpoint"]
    uri, headers, body = client.add_token(userinfo_endpoint)
    userinfo_response = requests.get(uri, headers=headers, data=body).json()
    user = User.query.filter_by(email=userinfo_response['email']).first()
    if not user:
        user = User(userinfo_response['email'],
                    username=userinfo_response['sub'], 
                    first_name=userinfo_response['given_name'],
                    last_name=userinfo_response['family_name'])
        db.session.add(user)
        db.session.commit()
    login_user(user)
    return redirect(url_for('users.home'))

@mod.route('/login/redirect')
@login_required
def login_redirect():
    if current_user.isEngineer():
        return redirect(url_for('users.engineer'))
    if current_user.isManager() or current_user.isAdmin():
        return redirect(url_for('users.dashboard'))
    return redirect(url_for('users.home'))
 
@mod.route('/logout/')
@login_required
def logout():
    logout_user()
    return redirect(url_for('users.login'))
  
@mod.route('/register/', methods=['GET', 'POST'])
def register():
    """
    Registration Form
    """
    if current_user.is_authenticated:
        return redirect(url_for('users.login_redirect'))    
    form = RegisterForm(request.form)
    if form.validate_on_submit():
        # check whether if there is user with the same username/email
        user = User.query.filter(or_(User.username == form.username.data, 
                                     User.email == form.email.data)).first()
        if not user:
            # create an user instance not yet stored in the database
            user = User(form.email.data, 
                        username=form.username.data, 
                        first_name=form.first_name.data, 
                        last_name=form.last_name.data, 
                        password=generate_password_hash(form.password.data))
            # Insert the record in our database and commit it
            db.session.add(user)
            db.session.commit()

            # Log the user in, as he now has an id
            login_user(user)

            # flash will display a message to the user
            flash('Thanks for registering')
            # redirect user to the 'home' method of the user module.
            return redirect(url_for('users.login_redirect'))
        flash('Username or email is taken.')
    return render_template("users/register.html", form=form)

@mod.route('/dashboard/')
@login_required
def dashboard():
    return render_template("users/dashboard.html")
    
@mod.route('/engineer/')
@login_required
def engineer():
    return render_template("users/engineer.html")
  
@mod.route('/admin/bookings', methods=['GET'])
@login_required
def admin_bookings():
    if not current_user.isAdmin():
        return "503 Not sufficent permission"
    bookings = Booking.query.all()
    return render_template("users/admin/bookings.html", bookings=bookings)

@mod.route('/admin/cars', methods=['GET'])
@login_required
def admin_cars():
    if not current_user.isAdmin():
        return "503 Not sufficent permission"
    cars = Car.query.all()
    return render_template("users/admin/cars.html", cars=cars)

@mod.route('/admin/cars/create', methods=['GET', 'POST'])
@login_required
def admin_cars_create():
    if not current_user.isAdmin():
        return "503 Not sufficent permission"
    form = CarForm(request.form)
    if form.validate_on_submit():
        car = Car(make=form.make.data, 
                  color=form.color.data,
                  body_type=form.body_type.data,
                  seats=form.seats.data,
                  cost_per_hour=form.cost_per_hour.data)
        # Insert the record in our database and commit it
        db.session.add(car)
        db.session.commit()
        flash('Car added.')
        return redirect(url_for('users.admin_cars_create'))
        # redirect user to the 'home' method of the user module.    
    return render_template("users/admin/cars-create.html", form=form)    

@mod.route('/admin/cars/edit/<car_id>', methods=['GET', 'POST'])
@login_required
def admin_cars_edit(car_id):
    if not current_user.isAdmin():
        return "503 Not sufficent permission"
    car = Car.query.filter_by(id=car_id).first()
    if not car: 
        return "400 car not exists"
    form = CarForm(obj=car)
    if form.validate_on_submit():
        form.populate_obj(car)
        db.session.commit()
        flash('Car information updated.')
    return render_template("users/admin/cars-edit.html", form=form)

@mod.route('/admin/cars/delete', methods=['POST'])
@login_required
def admin_cars_delete():
    if not current_user.isAdmin():
        return "503 Not sufficent permission", 503
    car = Car.query.filter_by(id=request.form['car_id']).first()
    if car:
        db.session.delete(car)
        db.session.commit()
        return '', 200
    return 'car not exist.', 404

@mod.route('/admin/cars/report', methods=['POST'])
@login_required
def admin_cars_report():
    if not current_user.isAdmin():
        return "503 Not sufficent permission", 503
    car = Car.query.filter_by(id=request.form['car_id']).first()
    if car:

masterpi/app/templates/users/booking-history.html
{% extends "base.html" %}
{% block content %}
<table style="width:100%">
    <tr>
      <th>car id</th>
      <th>duration</th>
      <th>time</th>
    </tr>
    {% for booking in bookings %}
        <tr>
            <td><a href={{ url_for('cars.details', id=booking.car_id) }}>{{ booking.car_id }}</a></td>
            <td>{{ booking.duration }}</td>
            <td>{{ booking.actions[0].creation_time }}</td>
        </tr>
    {% endfor %}
  </table>
{% endblock %}

masterpi/app/templates/users/dashboard.html
{% extends "base.html" %}
{% block content %}
<h1>Dashboard</h1>
{% endblock %}

masterpi/app/templates/users/engineer.html
{% extends "base.html" %}
{% block content %}
<h1>Engineer</h1>
{% endblock %}

masterpi/app/templates/users/home.html
{% extends "base.html" %}
{% block content %}
  <div class="jumbotron">
    <h1 class="display-3">Hello, {{ user.first_name if user.first_name else user.username }}!</h1>
    <p class="lead">It's nice to have you back with us. Have a nice day.</p>
    <hr class="my-4">
    <p class="lead">
      <a class="btn btn-secondary btn-lg shadow" href="{{ url_for('cars.index') }}" role="button">
        <i class="fa fa-car" aria-hidden="true"></i> Book a car
      </a>
    </p>
  </div>
  <div class="bs-docs-section">
    <div class="row">
      <div class="col-lg-12">
        <h1 class='page-header pb-3'>Your bookings:</h1>
      </div>
    </div>
    <div class="bs-component">

      <div class="row">
        
        {% for booking in bookings %}
        <div class="col-lg-4">
          <div class="card mb-3">
            <h4 class="card-header text-center"><a href={{ url_for('cars.details', id=booking.car_id) }}>{{ booking.car.make }}</a></h4>
            <ul class="list-group list-group-flush">
              <li class="list-group-item">duration: <b>{{ booking.duration }} hour(s)</b></li>
              {% for action in booking.actions %}
                <li class="list-group-item">{{ action.action }} <b class="timeago" datetime="{{ action.creation_time }}"></b></li>
              {% endfor %}
            </ul>
            <div id="booking-footer-{{ booking.id }}" class="card-footer justify-content-between text-muted">
              {% if booking.booked %}
                <button onclick="cancelBooking({{ booking.id }})" class="btn btn-danger card-link">
                  <i class="fa fa-ban" aria-hidden="true"></i> Cancel
                </button>
              {% elif booking.unlocked %}
                  <button onclick="returnCar({{ booking.id }})" class="btn btn-success float-right card-link">
                    <i class="fa fa-reply" aria-hidden="true"></i> Return
                  </button>
              {% else %}
                Booking finished.
              {% endif %}
            </div>
          </div>
        </div>
        {% else %}
        <div class="col-lg-12">
          <p>your booking history is empty :(</p>
        </div>
        {% endfor %}        
      </div>  
    </div>
  </div>
{% endblock %}

{% block script %}
{{ super() }}
<!-- Book btn handler -->
<script src="{{ url_for('static', filename='js/timeago.min.js') }}" type="text/javascript"></script>
<script>
  timeago().render(document.querySelectorAll('.timeago'));

  function cancelBooking(booking_id) {
      $.ajax({
          url: '{{ url_for("bookings.cancel") }}',
          data: {
              booking_id: booking_id
          },
          type: 'POST',
          success: function (res) {
              $('#booking-footer-' + booking_id).html("Booking cancelled.");
          }
      })
  }

  function returnCar(booking_id) {
      $.ajax({
          url: '{{ url_for("bookings.return_") }}',
          data: {
              booking_id: booking_id
          },
          type: 'POST',
          success: function (res) {
              $('#booking-footer-' + booking_id).html("Car returned.");
          }
      })
  }

</script>
{% endblock %}

masterpi/app/templates/users/login.html
{% extends "base.html" %}

{% block content %}

<div class="container">
     <div class="row">
        <div class="col-lg-6 d-none d-lg-block">
           <div class="page-header">
              <h1 id="forms">Car Share IOT</h1>
              <img src="{{ url_for('static', filename='img/hero.svg') }}" class="img-fluid hero-img" alt="hero">
           </div>
        </div>
        <div class="col-lg-6 mx-auto login-form">
           <div class="bs-component">
              <fieldset>
                 <legend><b>Login</b> / <a href="{{ url_for('users.register') }}">Register</a></legend>
                 <hr class="my-4">
                 <button type="button" class="btn btn-info btn-block btn-google">
                 <i class="fa fa-google" aria-hidden="true"></i> Sign in with Google
                 </button>
                 <hr class="my-4">
                 {% from "forms/macros.html" import render_field, render_checkbox %}
                 <form method="POST" action="." class="form">
                    {{ form.csrf_token }}
                    <div class="form-group">
                      <p class="text-danger">{{ get_flashed_messages()[-1] }}</p>
                    </div>
                    {{ render_field(form.username, class="form-control") }}
                    {{ render_field(form.password, class="form-control") }}
                    {{ render_checkbox(form.remember_me, class="custom-control-input") }}
                    <button type="submit" class="btn btn-primary btn-block">Login</button>
                 </form>
              </fieldset>
           </div>
        </div>
     </div>
</div>
{% endblock %}

masterpi/app/templates/users/photos-upload.html
{% extends "base.html" %}
{% block content %}
    {% if uploaded == False %}
        Please upload at least 3 portrait images for successful facial recognition.
        {% from "forms/macros.html" import render_field, render_checkbox %}
        <form method="POST" action="." enctype="multipart/form-data">
            {{ form.csrf_token }}
            {{ render_field(form.images, class="form-control") }}
            <button type="submit">Upload</button>
        </form>
    {% else %}
        <p>Upload completed</p>
    {% endif %}
{% endblock %}

masterpi/app/templates/users/profile.html
{% extends "base.html" %}
{% block content %}
  Hi {{ user.username }}! <br>
  Your role is "{{ user.getRole() }}" <br>
  <a href="{{ url_for('users.logout') }}">Logout</a>
{% endblock %}

masterpi/app/templates/users/register.html
{% extends "base.html" %}

{% block content %}

<div class="container-fluid h-100 pt-5">
    <div class="row justify-content-center align-items-center h-100">
      <div class="col-lg-6 d-none d-lg-block">
          <div class="page-header">
          <h1 id="forms">Car Share IOT</h1>
          <img src="{{ url_for('static', filename='img/hero.svg') }}" class="img-fluid hero-img" alt="hero">
          </div>
      </div>
      <div class="col-lg-6 mx-auto register-form shadow">
          <div class="bs-component">
          <fieldset>
              <legend><a href="{{ url_for('users.login') }}">Login</a> / <b>Register</b></legend>
              <hr class="my-4">
              {% from "forms/macros.html" import render_field, render_checkbox %}
              <form method="POST" action="." class="form">
                  {{ form.csrf_token }}
                  <div class="form-group">
                    <p class="text-danger">{{ get_flashed_messages()[-1] }}</p>
                  </div>                  
                  {{ render_field(form.username, class="form-control") }}
                  {{ render_field(form.email, class="form-control") }}
                  {{ render_field(form.password, class="form-control") }}
                  {{ render_checkbox(form.accept_tos, class="custom-control-input") }}
                  <button type="submit" class="btn btn-primary btn-block shadow">Register</button>
              </form>
          </fieldset>
      </div>
      </div>
  </div>
</div>

{% endblock %}